//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchData", Namespace="http://schemas.datacontract.org/2004/07/ItiWfcSelfHosted")]
    [System.SerializableAttribute()]
    public partial class BranchData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable branchsTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable configKeysTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable configTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable branchsTable {
            get {
                return this.branchsTableField;
            }
            set {
                if ((object.ReferenceEquals(this.branchsTableField, value) != true)) {
                    this.branchsTableField = value;
                    this.RaisePropertyChanged("branchsTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable configKeysTable {
            get {
                return this.configKeysTableField;
            }
            set {
                if ((object.ReferenceEquals(this.configKeysTableField, value) != true)) {
                    this.configKeysTableField = value;
                    this.RaisePropertyChanged("configKeysTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable configTable {
            get {
                return this.configTableField;
            }
            set {
                if ((object.ReferenceEquals(this.configTableField, value) != true)) {
                    this.configTableField = value;
                    this.RaisePropertyChanged("configTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentData", Namespace="http://schemas.datacontract.org/2004/07/ItiWfcSelfHosted")]
    [System.SerializableAttribute()]
    public partial class StudentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable configKeysTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable configTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable studentsTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable configKeysTable {
            get {
                return this.configKeysTableField;
            }
            set {
                if ((object.ReferenceEquals(this.configKeysTableField, value) != true)) {
                    this.configKeysTableField = value;
                    this.RaisePropertyChanged("configKeysTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable configTable {
            get {
                return this.configTableField;
            }
            set {
                if ((object.ReferenceEquals(this.configTableField, value) != true)) {
                    this.configTableField = value;
                    this.RaisePropertyChanged("configTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable studentsTable {
            get {
                return this.studentsTableField;
            }
            set {
                if ((object.ReferenceEquals(this.studentsTableField, value) != true)) {
                    this.studentsTableField = value;
                    this.RaisePropertyChanged("studentsTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstructorData", Namespace="http://schemas.datacontract.org/2004/07/ItiWfcSelfHosted")]
    [System.SerializableAttribute()]
    public partial class InstructorData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable InstructorsTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable configKeysTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable configTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable InstructorsTable {
            get {
                return this.InstructorsTableField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorsTableField, value) != true)) {
                    this.InstructorsTableField = value;
                    this.RaisePropertyChanged("InstructorsTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable configKeysTable {
            get {
                return this.configKeysTableField;
            }
            set {
                if ((object.ReferenceEquals(this.configKeysTableField, value) != true)) {
                    this.configKeysTableField = value;
                    this.RaisePropertyChanged("configKeysTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable configTable {
            get {
                return this.configTableField;
            }
            set {
                if ((object.ReferenceEquals(this.configTableField, value) != true)) {
                    this.configTableField = value;
                    this.RaisePropertyChanged("configTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBranchsData", ReplyAction="http://tempuri.org/IService1/getBranchsDataResponse")]
        ClientApplication.ServiceReference1.BranchData getBranchsData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBranchsData", ReplyAction="http://tempuri.org/IService1/getBranchsDataResponse")]
        System.Threading.Tasks.Task<ClientApplication.ServiceReference1.BranchData> getBranchsDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStudentsData", ReplyAction="http://tempuri.org/IService1/getStudentsDataResponse")]
        ClientApplication.ServiceReference1.StudentData getStudentsData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStudentsData", ReplyAction="http://tempuri.org/IService1/getStudentsDataResponse")]
        System.Threading.Tasks.Task<ClientApplication.ServiceReference1.StudentData> getStudentsDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInstructorsData", ReplyAction="http://tempuri.org/IService1/getInstructorsDataResponse")]
        ClientApplication.ServiceReference1.InstructorData getInstructorsData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getInstructorsData", ReplyAction="http://tempuri.org/IService1/getInstructorsDataResponse")]
        System.Threading.Tasks.Task<ClientApplication.ServiceReference1.InstructorData> getInstructorsDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientApplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientApplication.ServiceReference1.IService1>, ClientApplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApplication.ServiceReference1.BranchData getBranchsData() {
            return base.Channel.getBranchsData();
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ServiceReference1.BranchData> getBranchsDataAsync() {
            return base.Channel.getBranchsDataAsync();
        }
        
        public ClientApplication.ServiceReference1.StudentData getStudentsData() {
            return base.Channel.getStudentsData();
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ServiceReference1.StudentData> getStudentsDataAsync() {
            return base.Channel.getStudentsDataAsync();
        }
        
        public ClientApplication.ServiceReference1.InstructorData getInstructorsData() {
            return base.Channel.getInstructorsData();
        }
        
        public System.Threading.Tasks.Task<ClientApplication.ServiceReference1.InstructorData> getInstructorsDataAsync() {
            return base.Channel.getInstructorsDataAsync();
        }
    }
}
